version: '3.7'
services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
      - PGDATA=/var/lib/postgresql/data/pgdata
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - postgres:/var/lib/postgresql/data/pgdata

  webserver:
    build:
      context: ./docker
    restart: always
    depends_on:
      - postgres
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
      - FERNET_KEY=PeYlHn-Zy3m7MLxS8ryQjNlATOO4ZCNzYCHbEZLmUss=
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - ./volumes/dags:/usr/local/airflow/dags
      - ./volumes/plugins:/usr/local/airflow/plugins
      - ./volumes/libs:/usr/local/airflow/libs
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3

volumes:
  postgres:
